### ISSUE TITLE
Update .NET SDK to v8.0.402

### ISSUE THREAD

**Issue by mawl** [microsoft/dotnet-framework-docker#1174]
For the vs_buildtools component Microsoft.NetCore.Component.SDK, please update the installed .NET SDK Version to 8.0.402, see https://github.com/NuGet/Home/issues/13729 for details.

After that please update your .NET Framework SDK Dockerfiles, for example: https://github.com/microsoft/dotnet-framework-docker/blob/2d75ca9b3546b69e511e36a4b5d6a897a805506c/src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile#L37

BTW: 8.0.402 is already used for .NET SDK Dockerfiles, for example: https://github.com/dotnet/dotnet-docker/blob/b9bca757f5f6135feab16b7d7aac9e0e3f101e3b/src/sdk/8.0/windowsservercore-ltsc2022/amd64/Dockerfile

Many Thanks.

**Comment by lbussell** [comment]
[Triage] The version of the .NET SDK in the .NET Framework Dockerfiles tracks the version of the .NET SDK that's supported in the current Visual Studio version. .NET SDK out-of-band releases don't get inserted into Visual Studio. You can expect the next regular servicing version of the .NET SDK to be available in the .NET Framework images.

You may also manually install the latest version using the `dotnet-install` scripts: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

Closing this as not planned since we won't be changing the images to pick up the OOB 8.0.402 release.
