### ISSUE TITLE
Use PATH instead of setx

### ISSUE THREAD

**Issue by laoshancun** [microsoft/dotnet-framework-docker#1195]
### Describe the Bug
Docker BuildKit fails to recognize the PATH environment variable set via SETX, resulting in the failure of container building. BuildKit recommendation is to use PATH environment variable setting.
### Steps to Reproduce
- Dockerfile
```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8.1-windowsservercore-ltsc2022
```
- `docker buildx build .`
### Related Issues
[WCOW: support for setx, installers vs. ENV, a discussion](https://github.com/moby/buildkit/issues/5445)

**Comment by lbussell** [comment]
I see you are using BuildKit. Are you trying to use BuildKit's experimental support for WCOW? That is an unexplored space for us at the moment. If BuildKit becomes better supported then we can evaluate whether or not using `PATH` is feasible instead of `setx`.

If you are just trying to build an image, you should use the regular Docker builder until BuildKit is better supported for WCOW. If you are trying to experiment with BuildKit or work on BuildKit for WCOW, then this issue is better suited for the [microsoft/WindowsContainers](https://github.com/microsoft/Windows-Containers) repo.

Related documentation for BuildKit WCOW: https://github.com/moby/buildkit/blob/master/docs/windows.md
