### ISSUE TITLE
Unable to rebuild 3.5 docker image

### ISSUE THREAD

**Issue by johnhanks1** [Microsoft/dotnet-framework-docker#13]
Hello I was hoping to be able to rebuild the 3.5 docker image on my desktop. I'm unable to build this because I'm missing the install directory. Will you please checkin your install directory so that we can recreate the docker image locally?

**Comment by shirhatti** [comment]
@staceyhaffner @richlander Do you where customers can download the .NET 3.5 FoD cab package from?

**Comment by johnhanks1** [comment]
Any news on this. This is blocking my ability to adopt windows for docker. I have tried every online solution with no luck of getting 3.5 installed.

**Comment by kendrahavens** [comment]
Yes, we are trying to figure out how to help! There is an email thread discussing this. Sorry I should have posted here so you knew we were working on it. Typically we say use: 

```Dockerfile
FROM microsoft/dotnet-framework:3.5
```

Could you tell us more about your scenario and why you'd like to build it?

Also, I found [powershell commands](https://blogs.technet.microsoft.com/mniehaus/2015/08/31/adding-features-including-net-3-5-to-windows-10/) that you might be able to add to your container instead of the cab file, though I haven't tried it out myself.

**Comment by richlander** [comment]
@johnhanks1 Are you suggesting that you are trying to build the base image, as defined in this repo? If so, that won't work. The .cab referenced isn't a public artifact.

**Comment by kendrahavens** [comment]
@johnhanks1 I was wondering if you were still interested in this as a scenario or if the powershell install worked successfully?

If there is no further interest here, I can close this issue.
