### ISSUE TITLE
Install-WindowsFeature MSMQ-Server errors out

### ISSUE THREAD

**Issue by vjgn** [Microsoft/dotnet-framework-docker#151]
I have tried to install  MSMQ-Server using windowsservercore-ltsc2016 as well as windowsservercore-1709 (both 4.7.1 and 4.7.2 versions) and docker build always errors out with the following message:

> DISMAPI_Error__Failed_To_Enable_Updates,Microsoft.Windows.ServerManager.Commands.AddWindowsFeatureCommand

A simple docker file such as the one below can consistently reproduce this issue

```
# escape=`
FROM microsoft/aspnet:4.7.2-windowsservercore-1709
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Install-WindowsFeature MSMQ-Server;
```
Any help in resolving this is greatly appreciated.

**Comment by MichaelSimons** [comment]
It looks like installing MSMQ-Server within a container is not supported - see https://social.msdn.microsoft.com/Forums/en-US/bce99a7d-aa60-44fa-a348-450855650810/msmqserver-is-it-supported.

Closing as this issue is not specific to the microsoft/dotnet-framework images.  Feel free to continue the conversation.
