### ISSUE TITLE
Avoid switching between shells in Dockerfiles

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#251]
The Dockerfiles make use of the `SHELL` command to switch between either cmd or PowerShell.  Each `SHELL` command adds a layer to the image so we should avoid using it when possible.  However, all SDK images should set PowerShell as the default shell, so there needs to be at least one command to do that.

**Comment by MichaelSimons** [comment]
As part of fixing this, I see value in a larger Dockerfile refactoring to eliminate PS usage within the RUN instructions in general.  This solves a couple problems.

1. In the case of this specific issue, it is adding additional layers because of the need to switch the active SHELL being used.
1. It eliminates the mixture of PS and CMD syntax which doesn't help the readability at all.  
1. Right now the Dockerfiles aren't consistently checking the return value of the Start-Process calls.  The correctness is validated through latest stages (indirectly) and via testing.

If this were done, the recommendation would be to set PS as the default SHELL in the last Dockerfile instruction.
