### ISSUE TITLE
`host.docker.internal` is not accessible in Windows Server Core container.

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#351]
@stack247 commented on [Fri Jun 07 2019](https://github.com/microsoft/dotnet-framework-docker/issues/295)

## Issue

Using the following docker image, I'm not able to use `host.docker.internal` in any connection string (database or Azure Storage emulator).
* `mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019`
* `mcr.microsoft.com/dotnet/framework/aspnet:4.8`

## Background

I have an ASP.Net MVC web application (.Net Framework 4.6) that I containerized using the above-mentioned image. This application access database and Azure Storage that are running in the host. The host is running Docker for Windows and using Windows containers.

The issue is when the application runs, it won't be able to connect to any service in the host. I use `host.docker.internal` in the configuration file.

However, I was able to ping `host.docker.internal`.

In a separate test, `host.docker.internal` is accessible from a .Net Core application, running in Linux container and using the following image
* mcr.microsoft.com/dotnet/core/sdk:2.2-stretch

## Expected Result

Should be able to use `host.docker.internal` in connection string of the application that's running in a Windows container.

## Error

![image](https://user-images.githubusercontent.com/5100717/59082638-b8aa3300-88b9-11e9-8ea8-355a44d83d3d.png)

Tracer Route result

![image](https://user-images.githubusercontent.com/5100717/59082768-4128d380-88ba-11e9-94c8-38e4ec556f7e.png)

Ping result

![image](https://user-images.githubusercontent.com/5100717/59082831-746b6280-88ba-11e9-8ed1-258097fab4b8.png)

## Other Configurations

Host machine: Windows 10
Docker Desktop for Windows, version 2.0.0.3
Docker is running Windows container.

`Dockerfile` file
```
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
ARG source
WORKDIR /inetpub/wwwroot
COPY ${source:-obj/Docker/publish} .
```

Firewall is turned off
![image](https://user-images.githubusercontent.com/5100717/59082948-ea6fc980-88ba-11e9-9d1e-7f3d41a2b768.png)

**Comment by Heurazio** [comment]
Same problem here. Any solution to this?

**Comment by HongGit** [comment]
@mthalman isn't this an issue with Windows container, rather than ASP.NET container specific issue?  It seems the same issue persists for .NET core container as well?

**Comment by mthalman** [comment]
@HongGit - The original author explicitly says it does work in the .NET container:
> In a separate test, host.docker.internal is accessible from a .Net Core application, running in Linux container and using the following image
> mcr.microsoft.com/dotnet/core/sdk:2.2-stretch

**Comment by RichardChen1122** [comment]
@stack247 Since you can ping ` host.docker.internal` in container, means the configuration of your container is fine. If you still get error when connect the emulator service, please check the config of Azure Storage Emulator on the host.
By default, the emulator service is configured as being connected via localhost, to connect it remotely, you can update the StorageEmulatorConfig, change the highlights to the IP of your host (the exact IP return by ping `host.docker.internal`).
                 
![image](https://user-images.githubusercontent.com/10596709/72029811-13799200-32c2-11ea-93ba-c045ce620c41.png)


StorageEmulatorConfig file is the config of “Azure Storage Emulator”, you can find it under the installation path of the Emulator, on my box, it is at C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator.

Could you please try and see if it works for you?

**Comment by HongGit** [comment]
Thanks for reporting this issues!

Feel free to reactivate the issue if suggestion provided by @RichardChen1122 does not work for you.
