### ISSUE TITLE
Read environment variable through windows service

### ISSUE THREAD

**Issue by florianbaillagou** [microsoft/dotnet-framework-docker#365]
I have a small issue with my docker image, i would like to understand what's wrong with it.

I created a simple docker image based on microsoft/aspnet which declare an environment variable :

`ENV JAVA_HOME docker_file_value`

And i try to read it through a Windows service.

The service trace the environment variable :

`System.IO.File.WriteAllText(@"C:\log.txt", System.Environment.GetEnvironmentVariable("JAVA_HOME"));
`

My problem is that the value logged by the service match the environment variable from the **HOST** instead of the **container** (C:\Program files ...).

Is this a normal behaviour ? 

At worst, i would expect an empty value since services read environment variables stored in the registry and the registry is read only once by the service environment at system startup.

[Example.zip](https://github.com/Microsoft/aspnet-docker/files/2679699/Example.zip)

This is my Dockerfile :

> FROM microsoft/aspnet
ENV JAVA_HOME docker_file_value
ADD EchoEnv.exe /EchoEnv.exe
CMD sc.exe create EchoEnv binPath='c:\EchoEnv.exe' && sc start EchoEnv && c:\servicemonitor.exe w3svc && powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';
ENTRYPOINT ["cmd", "/c"]

**Comment by StephenMolloy** [comment]
@shirhatti?

**Comment by shirhatti** [comment]
Environment variables passed to docker are set for the process in the container via [`CreateProcess` and `lpEnvironment`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx).

They are not set as SYSTEM Variables which would reside in the registry in the `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment` hive and hence your Windows service can't read it.

As a workaround, you could create a SYSTEM variable by running `RUN setx /m VAR val` in your Dockerfile instead.

As for your other query on why the environment variables matches the host, I'm not sure that's expected behavior. I would ask on the [Windows Container forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).
