### ISSUE TITLE
August updates - looks like everything apart from 4.8 has reused July's tag

### ISSUE THREAD

**Issue by msperrin** [microsoft/dotnet-framework-docker#381]
Looking at https://mcr.microsoft.com/v2/dotnet/framework/aspnet/tags/list only 4.8 has a dated tag for this month (20190813).

Trying to Docker pull the image for 4.7.2 with what should be the correct date tag results in the following:

docker pull mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-20190813-windowsservercore-ltsc2019
Error response from daemon: manifest for mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-20190813-windowsservercore-ltsc2019 not found: manifest unknown: manifest unknown

When looking at 'docker image ls ' it appears the the July tag for 4.7.2 was updated 5 days ago and the same image ID is also used for the latest and windowsservercore-ltsc2019 tag.

mcr.microsoft.com/dotnet/framework/aspnet   4.7.2                                       **14e960e20513**        5 days ago          5.28GB
mcr.microsoft.com/dotnet/framework/aspnet   4.7.2-20190709-windowsservercore-ltsc2019   **14e960e20513**        5 days ago          5.28GB
mcr.microsoft.com/dotnet/framework/aspnet   4.7.2-windowsservercore-ltsc2019            **14e960e20513**        5 days ago          5.28GB

**Comment by mthalman** [comment]
That is intentional.  The only .NET Framework updates for the August Patch Tuesday release was for 4.8.  All other versions of .NET Framework, including 4.7.2, did not have updates.  However, the base Server Core image was updated which means we re-built all of the images.  That's why the images show that they were updated.  But we only update the tag if .NET Framework itself has been updated.
