### ISSUE TITLE
Why ltsc2016 images are much larger than 1803?

### ISSUE THREAD

**Issue by tonylife** [microsoft/dotnet-framework-docker#468]
Why ltsc2016 images are much larger than 1803?
Following is an example.
I am looking for small size image with .Net 4.7.2+.
Thanks.

mcr.microsoft.com/dotnet/framework/runtime   4.8-windowsservercore-ltsc2016         14GB
mcr.microsoft.com/dotnet/framework/runtime   4.7.2-windowsservercore-ltsc2016       13.4GB
microsoft/dotnet-framework                   4.7.2-runtime-windowsservercore-1803   6.14GB

**Comment by MichaelSimons** [comment]
@tonylife, The main issue when it comes to the size of the .NET Framework images is the base OS image.  The Windows team has been working to address the size of the base OS images since they were initially release via ltsc2016.  You can easily see this by pulling and checking the size of the base images.

```
> docker pull mcr.microsoft.com/windows/servercore:ltsc2016
  ltsc2016: Pulling from windows/servercore
  Digest: sha256:e2147ea4d43b7e634c3ca8d4b6f2fb366b081c8ea69aa0ecc6c08b7c3d405746
  Status: Image is up to date for mcr.microsoft.com/windows/servercore:ltsc2016
  mcr.microsoft.com/windows/servercore:ltsc2016
> docker pull mcr.microsoft.com/windows/servercore:1909
  1909: Pulling from windows/servercore
  Digest: sha256:8d89f487982ba44ad954d899e99056ce9e8be955bf01c78685d80d6ab6ac23a0
  Status: Image is up to date for mcr.microsoft.com/windows/servercore:1909
  mcr.microsoft.com/windows/servercore:1909
> docker inspect -f "{{ .Size}}" mcr.microsoft.com/windows/servercore:ltsc2016
  11140329894
> docker inspect -f "{{ .Size}}" mcr.microsoft.com/windows/servercore:1909
  4577977520
```

If you are looking for the smallest image, your best option is to go with the latest - 1909.
