### ISSUE TITLE
Problem with sdk image and build arguments

### ISSUE THREAD

**Issue by johnkit** [microsoft/dotnet-framework-docker#480]
I am not able to pass arguments to docker files using sdk:4.8 (I haven't tried other sdk versions). Using this Dockerfile:

```
# FROM hello-world:latest
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
ARG foo=bar
RUN echo Expected-substitution: $foo
RUN echo This-works-for-some-windows-images: %foo%
```

Running `docker build --no-cache` with or without `--build-arg` gives me the following output, with no sign of argument substitution, plus some unexpected new lines. Am I doing something wrong?

```
Sending build context to Docker daemon  65.57MB
Step 1/4 : FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
 ---> a7ec2e715ec5
Step 2/4 : ARG foo=bar
 ---> Running in 6227ab9c21c8
Removing intermediate container 6227ab9c21c8
 ---> 0d44f837af9d
Step 3/4 : RUN echo Expected-substitution: $foo
 ---> Running in 48636a3f7ecb
Expected-substitution:
Removing intermediate container 48636a3f7ecb
 ---> 6009cb267f18
Step 4/4 : RUN echo This-works-for-some-windows-images: %foo%
 ---> Running in 3f84af87769d
This-works-for-some-windows-images:
%foo%
Removing intermediate container 3f84af87769d
 ---> c492ff56eaae
Successfully built c492ff56eaae
```

**Comment by mthalman** [comment]
This is because the SDK images set PowerShell to be the default shell.  Example:
https://github.com/microsoft/dotnet-framework-docker/blob/430dfdaca4a3ce29c978528ab89dc9383fd9f94f/4.8/sdk/windowsservercore-1909/Dockerfile#L93

So you need to use PowerShell syntax to reference the `foo` environment variable:

```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
ARG foo=bar
RUN echo Expected-substitution: ${Env:foo}
```

Alternatively, you could change the default shell to `CMD` instead of PowerShell and things would work:

```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
ARG foo=bar
SHELL ["cmd", "/S", "/C"]
RUN echo Expected-substitution: %foo%
```

Closing.  Feel free to respond if this doesn't resolve your issue.
