### ISSUE TITLE
aspnet 4.7.2 SameSite=None Issue

### ISSUE THREAD

**Issue by CeilingCatSeesU** [microsoft/dotnet-framework-docker#514]
Hi,

I'm currently having issues when running web applications with the following image `mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019`. This doesn't seem to have KB4533013 fix applied to it so when we set a cookie to have the SameSite=None the cookie doesn't have this property value in the return web response. It works fine with the 'aspnet:4.8' image.

I copied the `System.Web.dll` from both containers and inspected them using dotPeek and the code is different (I'm Looking at method `System.Web.HttpCookie.GetSetCookieHeader`).

I would have thought the 4.7.2 image would contain (https://support.microsoft.com/en-us/help/4533013/kb4533013-cumulative-update-for-net-framework) since it was last updated on 14-1-2020?

Code snippets from inspecting:

4.7.2 -
`      if (this._sameSite != SameSiteMode.None)
      {
        stringBuilder.Append("; SameSite=");
        stringBuilder.Append((object) this._sameSite);
      }`

4.8 -
`      if (this._sameSite > (AppSettings.SuppressSameSiteNone ? SameSiteMode.None : ~SameSiteMode.None))
      {
        stringBuilder.Append("; SameSite=");
        stringBuilder.Append((object) this._sameSite);
      }`

My first time reporting a error, so if you need anymore info let me know.

Regards,

Aaron

**Comment by mthalman** [comment]
Updates for 4.7.2 on LTSC 2019 are applied in the base Windows image `mcr.microsoft.com/windows/servercore:ltsc2019`, so there's not an issue in the .NET Dockerfile.  I've verified that the 4.7.2 ASP.NET image is up-to-date with the latest base Windows image.

@HongGit - Could you investigate this?

**Comment by MichaelSimons** [comment]
@CeilingCatSeesU - Can you share the Id or digest of the 4.7.2 image you are using?

`docker inspect mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019 --format "{{ .ID }}"`

**Comment by CeilingCatSeesU** [comment]
Hi, @MichaelSimons here is the ID `sha256:ade24f19b13fe8818db27c86fb750b795000217e22594b87c04ae852ab360328`

**Comment by HongGit** [comment]
@mthalman  and @MichaelSimons it seems that the dotnet runtime image did not install the latest KB for .NET 4.7.2.

For 4.8 runtime docker, kb4534131 is applied.  However, it's corresponding kb4534119 is missing in the runtime docker image.

**Comment by HongGit** [comment]
@mthalman and @MichaelSimons it seems that the dotnet runtime image did not install the latest KB for .NET 4.7.2.

For 4.8 runtime docker, kb4534131 is applied. However, it's corresponding kb4534119 is missing in the 4.7.2 runtime docker image.

**Comment by mthalman** [comment]
@HongGit - It's not necessary for the `4.7.2-windowsservercore-ltsc2019` image to install a KB patch.  4.7.2 is already pre-installed in the base Windows image so that's where any patches should be included.

**Comment by HongGit** [comment]
@mthalman the fact is that kb4534119 is missing in 4.7.2 image, which is why this issue is surfaced.  The kb should be included either in windows image or the runtime image.  I see that 4.8 runtime Dockerfile has this line, which means that the runtime image installs patched on top of windows base image:

   DISM /Online /Quiet /Add-Package /PackagePath:C:\patch\windows10.0-kb4534131-x64-ndp48.cab

If you think windows base image should has kb4534119, should this issue be transferred to windows forum?

**Comment by mthalman** [comment]
@HongGit - I'm not denying the fact that it's not installed.  I'm just saying that installing it within the runtime Dockerfile is not where it should be done.  The 4.8 runtime Dockerfile is responsible for installing the patch because it's also explicitly installing 4.8 since the base Windows image does not have 4.8.  But in the case of 4.7.2, that version is already installed in the base Windows image and so it should be patched accordingly.

Since this particular issue is related to ASP.NET, my request is that you follow up with the Windows team to determine why this is not included in the base `ltsc2019` image.  I've looked at the KB history for the Server releases and I see that the [Dec 2019 KB for Windows Server 2019](https://support.microsoft.com/en-us/help/4464619) makes no mention of SameSite but it is mentioned in the [KB for Windows Server 2016](https://support.microsoft.com/en-us/help/4530689/windows-10-update-kb4530689).

**Comment by HongGit** [comment]
@CeilingCatSeesU  as a workaround, you could install kb4534119 in your image, which should have the correct package for the SameSite issue.

In the mean time, we will figure out where the disconnect is.

**Comment by CeilingCatSeesU** [comment]
@HongGit Fyi I have installed the KB update into my image but now it is causing web applications to give 503 service not running due to a error in .NET Runtime. 

I'm currently looking into why but it has only started with the KB being installed
```
PS C:\Users\aaron.barnett> docker exec 529e574f1f57   powershell " Get-EventLog -LogName Application -EntryType Error -Newest 1 | Select-Object  -Property *"                                 
EventID            : 1023
MachineName        : 529e574f1f57
Data               : {}
Index              : 93
Category           : (0)
CategoryNumber     : 0
EntryType          : Error
Message            : Application: w3wp.exe
                     Framework Version: v4.0.30319
                     Description: The process was terminated due to an
                     internal error in the .NET Runtime at IP 735119BE
                     (73500000) with exit code 80131506.
Source             : .NET Runtime
ReplacementStrings : {Application: w3wp.exe
                     Framework Version: v4.0.30319
                     Description: The process was terminated due to an
                     internal error in the .NET Runtime at IP 735119BE
                     (73500000) with exit code 80131506.
                     }
InstanceId         : 1023
TimeGenerated      : 3/6/2020 8:45:15 AM
TimeWritten        : 3/6/2020 8:45:15 AM
UserName           :
Site               :
Container          :
```
The KB was installed like this:
```
RUN curl.exe --output 'windows10.0-kb4534119.msu' 'http://download.windowsupdate.com/c/msdownload/update/software/updt/2020/01/windows10.0-kb4534119-x64_a2dce2c83c58ea57145e9069f403d4a5d4f98713.msu'; mkdir kb4534119; expand.exe -F:* windows10.0-kb4534119.msu C:\kb4534119; rm windows10.0-kb4534119.msu; DISM /Online /Quiet /Add-Package /PackagePath:C:\kb4534119\Windows10.0-KB4534119-x64.cab; rm -Recurse kb4534119
```

**Comment by mthalman** [comment]
This should now be fixed as part of yesterday's [release](https://github.com/microsoft/dotnet-framework-docker/issues/533).
