### ISSUE TITLE
Consider including Microsoft.VisualStudio.Workload.WebBuildTools in dotnet-framework-build image

### ISSUE THREAD

**Issue by samcook** [Microsoft/dotnet-framework-docker#60]
Hi

Adding `Microsoft.VisualStudio.Workload.WebBuildTools` to the `vs_BuildTools.exe` install command in the `dotnet-framework-build` image would allow the builder image to be used more easily for publishing web deployments.

e.g.
```
FROM microsoft/dotnet-framework-build:4.7.1 as builder

WORKDIR /app
COPY . ./
RUN ["nuget.exe", "restore"]
RUN ["msbuild.exe", "Foo.sln", "/p:Configuration=Release", "/p:DeployOnBuild=true", "/p:PublishProfile=Disk"]

FROM microsoft/aspnet:4.7.1
COPY --from=builder /app/published /inetpub/wwwroot
```

**Comment by MichaelSimons** [comment]
@samcook - Yes this is a scenario we plan to support.  The current plan is to add a build images within the microsoft/aspnet repo that are based on the microsoft/dotnet-framework-build images.  We would like to maintain separation between the two in order to limit the size of the microsoft/dotnet-framework-build images for non-aspnet scenarios.  The microsoft/aspnet work is being tracked with https://github.com/Microsoft/aspnet-docker/issues/63.  We are open to feedback anyone has on the build images.  Thanks
