### ISSUE TITLE
dotnet/framework/runtime:4.8 images missing for december updates

### ISSUE THREAD

**Issue by freddydk** [microsoft/dotnet-framework-docker#694]
The Monthly Windows Server Core versions was shipped a few days ago and the 4.8 images have still not shipped.
Looks like only ltsc2016 image was updated for 20201208

docker pull mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-20H2

still returns november update.

**Comment by MichaelSimons** [comment]
The .NET images were rebuilt in December to pick up the base OS updates.  The following two snippets illustrate how the .NET base layers are identical to the Windows base image.

```console
> docker pull mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-20H2
4.8-windowsservercore-20H2: Pulling from dotnet/framework/runtime
18ae6bebe21d: Already exists
65fc739778c5: Pull complete
62d11b6ffc11: Pull complete
3f32f3b01e43: Pull complete
4eba68e8c625: Pull complete
Digest: sha256:10c045b8fcaf45bace7913be38c11da52c0932b4d6295716c296bf261d1fb253
Status: Downloaded newer image for mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-20H2
mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-20H2
```

```console
> docker pull mcr.microsoft.com/windows/servercore:20H2
20H2: Pulling from windows/servercore
18ae6bebe21d: Already exists
65fc739778c5: Already exists
Digest: sha256:18e5eceed76bc625150cac184223af079bf3e833f1897bf21283ffbaa6b552dd
Status: Downloaded newer image for mcr.microsoft.com/windows/servercore:20H2
mcr.microsoft.com/windows/servercore:20H2
```

There were no .NET patches released this month which is why the timestamp wasn't updated for most .NET images.  This policy is described in the [.NET image tagging policy](https://github.com/microsoft/dotnet-framework-docker/blob/master/documentation/tagging-guidelines.md#tag-parts).  The timestamps were updated for the `ltsc2016` images due to the way the images are built and how .NET gets patched.  In 2016, .NET gets patched by the OS LCU which means the images need to always apply the latest LCU so there was a changes to the .NET layers so the timestamp was rev'd.

**Comment by freddydk** [comment]
Ok, sorry, I have misunderstood that.
This means that come end January, I will not be able to find the .net 4.8 built on the windows server core from december anymore as this tag will be overwritten - right?

**Comment by freddydk** [comment]
I will have to change my build scripts to just go for latest then instead of the tagged ones.

**Comment by MichaelSimons** [comment]
Correct, we only provide tags that allows you to isolate yourself from .NET component changes.  If you want to isolate yourself from any type of change, then our recommendation is to use an image digests rather than tags.

**Comment by freddydk** [comment]
Thank. and I assume that the dotnet framework images are then auto-rebuild right after the servercore images have shipped right?

**Comment by MichaelSimons** [comment]
We get notified internally when the Windows images are updated which then triggers the workflow to update the .NET images.

**Comment by freddydk** [comment]
Thanks

**Comment by freddydk** [comment]
BTW - do you know if I can get notified when you rebuild and trigger a build of my Business Central Images?

**Comment by MichaelSimons** [comment]
ACR tasks can be utilized to rebuild images when base images are updated - https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview#automate-os-and-framework-patching
