### ISSUE TITLE
Docker Image microsoft/aspnet:4.8-windowsservercore-ltsc2016 does not exist

### ISSUE THREAD

**Issue by Cloudmersive** [microsoft/dotnet-framework-docker#738]
4.8 is not working:

```
docker pull microsoft/aspnet:4.8-windowsservercore-ltsc2016
Error response from daemon: manifest for microsoft/aspnet:4.8-windowsservercore-ltsc2016 not found: manifest unknown: ma
nifest unknown
```

4.7.2 is working:

```
docker pull microsoft/aspnet:4.7.2-windowsservercore-ltsc2016
4.7.2-windowsservercore-ltsc2016: Pulling from microsoft/aspnet
Digest: sha256:cb1c9fffae6746eb89c39d3847abf52c7137b709f4fcbe8e886933db412bfa49
Status: Image is up to date for microsoft/aspnet:4.7.2-windowsservercore-ltsc2016
docker.io/microsoft/aspnet:4.7.2-windowsservercore-ltsc2016
```

According to documentation, 4.8 should exist:

https://hub.docker.com/_/microsoft-dotnet-framework-aspnet/

This is a serious issue!

**Comment by mthalman** [comment]
The [link](https://hub.docker.com/_/microsoft-dotnet-framework-aspnet/) you reference describes the tag you should be using: `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2016`.  You're referencing the old Docker Hub repositories which do not include 4.8 tags.  The publishing of all .NET tags had migrated from Docker Hub to [MCR](https://github.com/dotnet/announcements/issues/101) prior to the release of .NET Framework 4.8.  All new tags published since then have only been available from the MCR repositories.  But tags that were previously available from the Docker Hub repositories are still being kept up-to-date.

So, to resolve your issue, please update all your to use documented tags at https://hub.docker.com/_/microsoft-dotnet-framework-aspnet/.
