### ISSUE TITLE
When using Move-Item the file vanishes in recent SDK tags

### ISSUE THREAD

**Issue by pbering** [microsoft/dotnet-framework-docker#823]
### Describe the Bug

Something in the `mcr.microsoft.com/dotnet/framework/sdk:4.8` image has changed recently (or in any of it's base images), we have multiple failing builds due the use of `Move-Item`.

### Steps to Reproduce

```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR /dump
RUN New-Item -Path '.\test.txt' -ItemType 'File' | Out-Null
RUN Get-ChildItem -Path '.'
RUN Move-Item -Path '.\test.txt' -Destination '.\woop.txt' -Force -Verbose; Get-ChildItem -Path '.'
RUN Get-ChildItem -Path '.'
```

Run: 

```
docker image build . --no-cache
```

See that the output of step 6 shows the file is present at `C:\dump\woop.txt`, but the otutput of step 7 shows that is has **vanished**:

```
Step 6/7 : RUN Move-Item -Path '.\test.txt' -Destination '.\woop.txt' -Force -Verbose; Get-ChildItem -Path '.'
 ---> Running in d0abff633317
VERBOSE: Performing the operation "Move File" on target "Item: C:\dump\test.txt
 Destination: C:\dump\woop.txt".


    Directory: C:\dump


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/20/2021  12:06 PM              0 woop.txt


Removing intermediate container d0abff633317
 ---> a0a4a44d4bec
Step 7/7 : RUN Get-ChildItem -Path '.'
 ---> Running in ab058d2b60ce
Removing intermediate container ab058d2b60ce
```

Changing the base image to `FROM mcr.microsoft.com/windows/servercore:ltsc2019` instead, then the file is there in step 7 as expected:

```
Step 7/7 : RUN Get-ChildItem -Path '.'
 ---> Running in 7bde94fc2254


    Directory: C:\dump


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/20/2021  11:57 AM            (0) woop.txt


Removing intermediate container 7bde94fc2254
 ---> cd8affcf2e6c
```

### Other Information

- Workaround: Use `Copy-Item` instead of `Move-Item`.

### Output of `docker version`

```
Docker version 20.10.8, build 3967b7d
```

### Output of `docker info`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 15
  Running: 7
  Paused: 0
  Stopped: 8
 Images: 392
 Server Version: 20.10.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Enterprise Version 2009 (OS Build 19043.1165)
 OSType: windows
 Architecture: x86_64
 CPUs: 24
 Total Memory: 63.92GiB
 Name: AMD-3900X
 ID: XOLD:2WB6:4RSC:E7XQ:ZYFB:TENF:IQSS:R2SD:FTIF:PSN2:TWQQ:UEGT
 Docker Root Dir: D:\Data\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by pbering** [comment]
Just found out that `mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019` works as excepted, so it seems to be "only" `mcr.microsoft.com/dotnet/framework/sdk:4.8` that is broken...

**Comment by pbering** [comment]
These tags are broken as well:

```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8
```

But `FROM mcr.microsoft.com/windows/servercore/iis` is not...

**Comment by mthalman** [comment]
You get this same behavior if you use `mcr.microsoft.com/windows/servercore:ltsc2016` as the base. So it's not specific to the .NET images but rather some interaction between PowerShell and Windows Server 2016 containers.  I would suggest logging an issue at https://github.com/microsoft/Windows-Containers/issues.

This does require further explanation because there's the remaining question of why does pulling the `mcr.microsoft.com/dotnet/framework/sdk:4.8` tag give you a Windows Server 2016 container since you are running on the latest Windows version for your host.  This is due to the behavior of Docker.  The `4.8` tag being referenced is what is known as a multi-arch tag which Docker dynamically resolves to a Windows container that is [compatible](https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/version-compatibility) with the version of your Windows host. In your case, you are running this on a Windows 10 version 21H1 host.  Since we have not published a Windows container image that matches that host version (build 19043), Docker _falls back_ to the first entry in multi-arch image list, which happens to be a Windows Server 2016 container image. In fact, there is no version of Windows containers that corresponds to build 19043 so it's not even possible for us to publish a container image that your host system will match according to the Docker multi-arg tag resolution behavior.

In CI/CD or production scenarios, you wouldn't run into this situation assuming that those scenarios would be using Windows Server and not Windows 10.  But because you're running this on a Windows 10 desktop system, this can happen.  The workaround would be to explicitly set the tag to the target Windows version (e.g. 4.8-windowsservercore-20H2).

For now, we'll keep this issue open to see if the usability can be improved here.

**Comment by pbering** [comment]
Thank you for such a detailed answer and it kind of makes sense (strange to default to 2016 tough) - I did not realise that I was getting the 2016 version. I think it is appropriate to close this issue here.
