### ISSUE TITLE
Missing DOTNET_RUNNING_IN_CONTAINER environment variable in 2019 .NET Framework 4.8 SDK image

### ISSUE THREAD

**Issue by jc1001** [microsoft/dotnet-framework-docker#843]
Hi there,

When looking at the environment variables for the following 2022 .NET Framework 4.8 SDK Docker image `mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2022` (https://github.com/microsoft/dotnet-framework-docker/blob/9869625a843c05965b54fca903bfaa2f42bca069/src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile), I can see an environment variable for `DOTNET_RUNNING_IN_CONTAINER=true`. This variable is inherited from the runtime image (https://github.com/microsoft/dotnet-framework-docker/blob/dc98c2301d0d5e492fe8c699dbbd8926bbc9a823/src/runtime/4.8/windowsservercore-ltsc2022/Dockerfile).

If I however look at the 2019 .NET Framework 4.8 SDK Docker image `mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019` (https://github.com/microsoft/dotnet-framework-docker/blob/9869625a843c05965b54fca903bfaa2f42bca069/src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile), this environment variable does not seem to be present. 

I am not sure if there are any other missing environment variables, as this is the only one that I was looking for. If you require anything else, please let me know.

**Comment by mthalman** [comment]
Triage: This is by design. The environment variable was not introduced in these Dockerfiles until after Windows Server 2019 images had initially been published. Adding the environment variable would have been a breaking change in Windows Server 2019 and for that reason was only done for later versions of Windows Server.

Related to https://github.com/microsoft/dotnet-framework-docker/issues/452
