### ISSUE TITLE
Cannot build the docker sample on the microsoft git page

### ISSUE THREAD

**Issue by babusuresh74** [microsoft/dotnet-framework-docker#960]
### Describe the Bug

 I am trying the sample
https://github.com/microsoft/dotnet-framework-docker/blob/main/samples/aspnetmvcapp/README.md

and getting a  an error 
'msbuild' is not recognized as an internal or external command,
operable program or batch file.

It looks like msbuild is not in the container system but I don't know how to get it there.

### Steps to Reproduce
On the section  "Build and run the sample with **Docker**"
when try the command  :

docker build --pull -t aspnetmvcapp .

I get an error
'msbuild' is not recognized as an internal or external command,
operable program or batch file.

### Other Information

Following is the docker file.

```Dockerfile
FROM   mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetmvcapp/*.csproj ./aspnetmvcapp/
COPY aspnetmvcapp/*.config ./aspnetmvcapp/


# copy everything else and build app
COPY aspnetmvcapp/. ./aspnetmvcapp/
WORKDIR /app/aspnetmvcapp
RUN msbuild /p:Configuration=Release -r:False


FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /inetpub/wwwroot
COPY --from=build /app/aspnetmvcapp/. ./
```

**Comment by mthalman** [comment]
It looks like you've modified the Dockerfile from the version that exists in this repo. You've changed the image tag to be `mcr.microsoft.com/dotnet/sdk:6.0` instead of `mcr.microsoft.com/dotnet/framework/sdk:4.8`. If you follow the sample with the unmodified files from the repo it should work just fine.

Note that `mcr.microsoft.com/dotnet/sdk:6.0` is from the https://github.com/dotnet/dotnet-docker repo, which contains Dockerfiles for .NET/.NET Core. That's different from .NET Framework which is what this repo is for.
